---
- name: create required directories
  file: state=directory name={{ item }}
  with_items:
      - "{{ ext_statsdaemon_volume }}/conf"
      - "{{ ext_statsdaemon_volume }}/log"

- name: start a statsdaemon container
  docker:
    command: /bin/statsdaemon -graphite={{ graphite_address }} -opentsdb={{ opentsdb_address }}
    image: gitinsky/statsdaemon:latest
    state: reloaded
    hostname: "statsdaemon-{{ ansible_hostname }}"
    dns: "{{ docker_dns_servers }}"
    expose:
      - "{{ statsdaemon_port }}/udp"
    ports:
        - "{{ statsdaemon_listen_address + ':' if statsdaemon_listen_address is defined else '' }}{{ statsdaemon_port }}:{{ statsdaemon_port }}/udp"
    name: statsdaemon
    restart_policy: always
